"""Add 'deleted' column to Event

Revision ID: 4ece8eb7eece
Revises: 8ed2b463249b
Create Date: 2023-07-16 12:13:51.450754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ece8eb7eece'
down_revision = '8ed2b463249b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
