"""Add push_token column to User

Revision ID: 80619534b84e
Revises: ed9695a82642
Create Date: 2023-07-16 17:56:49.164414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80619534b84e'
down_revision = 'ed9695a82642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('notify_me')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_token', sa.String(length=100), nullable=True))
        batch_op.drop_column('onesignal_player_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onesignal_player_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('push_token')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_me', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
